# Generated by Django 4.1 on 2022-08-25 15:58

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('phone', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='images/')),
                ('location', models.TextField(max_length=250)),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('condition', models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Used', 'Used')], max_length=15)),
                ('isReserved', models.BooleanField(default=False)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='donation.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annoucement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=15)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1), null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Used', 'Used'), ('any', 'any')], max_length=15)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annoucement', to='donation.category')),
                ('charity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annoucement', to='donation.charity')),
            ],
        ),
    ]
